env:
  RUSTFLAGS: -D warnings

stable_test_task:
  name: "Rust Stable"
  container:
    image: rust:latest
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  setup_script:
    - rustup component add rustfmt
  primary_test_script:
    - rustc --version
    - cargo test --all
  without_backtrace_test_script:
    - cargo test --manifest-path compatibility-tests/without-backtrace/Cargo.toml
  futures_0.1_test_script:
    - cargo test --manifest-path compatibility-tests/futures-0.1/Cargo.toml
  compile_fail_test_script:
    - cargo test --manifest-path compatibility-tests/compile-fail/Cargo.toml
  lint_script:
    - cargo fmt --all -- --check
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_test_task:
  name: "Rust Nightly"
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  primary_test_script:
    - cargo +nightly test
  minimum_version_test_script:
    - cargo +nightly -Z minimal-versions update
    # These versions determined by trial and error
    - cargo +nightly update -p backtrace-sys --precise 0.1.20
    - cargo +nightly update -p libc --precise 0.2.7
    - cargo +nightly test
  futures_test_script:
    - cd compatibility-tests/futures/
    - rustc --version
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

v1_34_test_task:
  name: "Rust 1.34"
  container:
    image: rust:1.34
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  primary_test_script:
    - cd compatibility-tests/v1_34/
    - rustc --version
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

v1_30_test_task:
  name: "Rust 1.30"
  container:
    image: rust:1.30
    cpu: 1
    memory: 2Gi
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  primary_test_script:
    - cd compatibility-tests/v1_30/
    - rustc --version
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
