[package]
name = "snafu-derive"
version = "0.5.0"
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
edition = "2018"

description = "An ergonomic error handling library"
documentation = "https://docs.rs/snafu"
repository = "https://github.com/shepmaster/snafu"

license = "MIT OR Apache-2.0"

[features]
backtraces = []

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.19", features = ["full"] }
quote = "0.6"
proc-macro2 = "0.4"
